// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppConfigSnapshot {
    "adb_path": string;
    "fastboot_path": string;
    "scrcpy_path": string;
    "setup_completed": boolean;
    "theme": string;
    "binary_versions": { [_ in string]?: string } | null;
    "device_nicknames": { [_ in string]?: string } | null;
    "logcat_buffer_limit": number;
    "scrcpy_options": ScrcpyOptions;
    "scrcpy_presets": ScrcpyPreset[] | null;
    "default_terminal_mode": string;
    "auto_refresh_devices": boolean;
    "device_refresh_seconds": number;
    "audit_enabled": boolean;
}

/**
 * BinaryInfo describes a discovered binary candidate.
 */
export interface BinaryInfo {
    "name": string;
    "path": string;
    "source": string;
    "status": BinaryStatus;
    "version"?: string;
    "reason"?: string;
}

/**
 * BinaryStatus describes the readiness state of an external binary.
 */
export enum BinaryStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BinaryMissing = "missing",
    BinaryInvalid = "invalid_path",
    BinaryReady = "ready",
};

export interface PreferencesPayload {
    "theme": string;
    "device_nicknames": { [_ in string]?: string } | null;
    "logcat_buffer_limit": number;
    "scrcpy_presets": ScrcpyPreset[] | null;
    "default_terminal_mode": string;
    "auto_refresh_devices": boolean;
    "device_refresh_seconds": number;
    "audit_enabled"?: boolean | null;
}

export interface RuntimeDiagnostics {
    "os": string;
    "arch": string;
    "data_dir": string;
    "config_path": string;
    "managed_binary_dir": string;
    "setup_completed": boolean;
    "theme": string;
    "binary_versions": { [_ in string]?: string } | null;
    "capabilities": { [_ in string]?: boolean } | null;
}

export interface ScrcpyOptions {
    "max_size": number;
    "bit_rate": number;
    "max_fps": number;
    "audio_bit_rate": number;
    "audio_codec": string;
    "video_codec": string;
    "show_touches": boolean;
    "no_audio": boolean;
    "no_control": boolean;
    "stay_awake": boolean;
    "turn_screen_off": boolean;
    "power_off_on_close": boolean;
    "fullscreen": boolean;
    "always_on_top": boolean;
    "disable_screensaver": boolean;
    "rotation": number;
    "display_id": number;
    "time_limit": number;
}

export interface ScrcpyPreset {
    "name": string;
    "options": ScrcpyOptions;
}

export interface WirelessHistoryEntry {
    "address": string;
    "name": string;
}
