// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ProgressEvent {
    "name": string;
    "percent": number;
    "bytesReceived": number;
    "bytesTotal": number;
    "status": string;
}
