// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

export type BinaryInfo = core$0.BinaryInfo;

export interface BinarySetupResult {
    "adb": BinaryInfo | null;
    "fastboot": BinaryInfo | null;
    "scrcpy": BinaryInfo | null;
    "ready": boolean;
    "adbCandidates": BinaryInfo[] | null;
    "fastbootCandidates": BinaryInfo[] | null;
    "scrcpyCandidates": BinaryInfo[] | null;
}

export interface SetupState {
    "status": BinarySetupResult | null;
    "setupCompleted": boolean;
    "canFinish": boolean;
}
