// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as download$0 from "../../../../../ADBKit/internal/download/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as file$0 from "../../../../../ADBKit/internal/file/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as flasher$0 from "../../../../../ADBKit/internal/flasher/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as scrcpy$0 from "../../../../../ADBKit/internal/scrcpy/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as shell$0 from "../../../../../ADBKit/internal/shell/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "binary_download_progress": download$0.ProgressEvent;
            "file_transfer_progress": file$0.TransferProgress;
            "files-dropped": string[] | null;
            "flash_step_status": flasher$0.StepStatus;
            "logcat_line": shell$0.LogcatEntry;
            "logcat_status": shell$0.LogcatStatusEvent;
            "scrcpy_error": scrcpy$0.SessionEvent;
            "scrcpy_session_started": scrcpy$0.SessionEvent;
            "scrcpy_session_stopped": scrcpy$0.SessionEvent;
            "terminal_closed": { [_ in string]?: string } | null;
            "terminal_output": { [_ in string]?: string } | null;
        }
    }
}
