// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as audit$0 from "../audit/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as binary$0 from "../binary/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as device$0 from "../device/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dialog$0 from "../dialog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as file$0 from "../file/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as flasher$0 from "../flasher/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as launcher$0 from "../launcher/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as packagemgr$0 from "../package_mgr/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scrcpy$0 from "../scrcpy/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as shell$0 from "../shell/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tuning$0 from "../tuning/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../updater/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AnalyzeSafeTuning(profileID: string): $CancellablePromise<tuning$0.Analysis> {
    return $Call.ByID(3542972997, profileID);
}

export function AnalyzeSafeTuningForDevice(serial: string, profileID: string): $CancellablePromise<tuning$0.Analysis> {
    return $Call.ByID(1910898522, serial, profileID);
}

/**
 * ApplyLauncher performs the confirmed HOME replacement. The request carries the
 * client-generated operation ID so the caller can cancel while this call runs.
 */
export function ApplyLauncher(request: launcher$0.ApplyRequest): $CancellablePromise<launcher$0.ApplyResult> {
    return $Call.ByID(3779371605, request);
}

export function ApplySafeTuning(request: tuning$0.ApplyRequest): $CancellablePromise<tuning$0.ApplyResult> {
    return $Call.ByID(2851340301, request);
}

export function AutoConnectWireless(selector: string): $CancellablePromise<device$0.WirelessConnectResult> {
    return $Call.ByID(2589474954, selector);
}

/**
 * AutoReconnectRememberedWireless discovers the current dynamic ADB endpoints
 * once and reconnects remembered TVs that are not already ready in adb devices.
 */
export function AutoReconnectRememberedWireless(): $CancellablePromise<$models.WirelessReconnectReport> {
    return $Call.ByID(1362127067);
}

export function CancelFileTransfer(): $CancellablePromise<void> {
    return $Call.ByID(3540445436);
}

export function CancelFileTransferFor(operationID: string): $CancellablePromise<void> {
    return $Call.ByID(2859205779, operationID);
}

/**
 * CancelLauncherOperation signals the owned operation. It intentionally skips the
 * admission check: the operation ID and the explicit serial must match, and the
 * current global selection is irrelevant.
 */
export function CancelLauncherOperation(request: launcher$0.CancelRequest): $CancellablePromise<launcher$0.CancelResult> {
    return $Call.ByID(3409198126, request);
}

export function CaptureScreenshot(serial: string, localPath: string): $CancellablePromise<device$0.ScreenshotResult> {
    return $Call.ByID(3411385027, serial, localPath);
}

export function CheckForUpdates(): $CancellablePromise<updater$0.ReleaseInfo> {
    return $Call.ByID(3155932570);
}

export function ClearAuditLogs(): $CancellablePromise<void> {
    return $Call.ByID(1675299564);
}

export function ClearCustomBinary(name: string): $CancellablePromise<void> {
    return $Call.ByID(2476663758, name);
}

export function ClearDeviceNickname(serial: string): $CancellablePromise<void> {
    return $Call.ByID(3549130150, serial);
}

export function ClearPackageData(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(875953584, packageName);
}

export function ClearPackageDataForDevice(expectedSerial: string, packageName: string): $CancellablePromise<string> {
    return $Call.ByID(2026764277, expectedSerial, packageName);
}

export function CloseTerminal(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(4124276905, sessionID);
}

export function CompleteSetup(): $CancellablePromise<binary$0.SetupState | null> {
    return $Call.ByID(455247985);
}

export function ConfigureSafeTuningFeed(config: tuning$0.FeedConfig): $CancellablePromise<tuning$0.FeedStatus> {
    return $Call.ByID(207582333, config);
}

export function ConnectWireless(address: string): $CancellablePromise<string> {
    return $Call.ByID(1774714983, address);
}

export function CreateDirectory(remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(2415799174, remotePath);
}

export function CreateDirectoryForDevice(expectedSerial: string, remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(3217079483, expectedSerial, remotePath);
}

export function DeleteFile(remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(1355371458, remotePath);
}

export function DeleteFileForDevice(expectedSerial: string, remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(3109305791, expectedSerial, remotePath);
}

export function DeleteMultipleFiles(remotePaths: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(3099217239, remotePaths);
}

export function DeleteMultipleFilesForDevice(expectedSerial: string, remotePaths: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(3022224996, expectedSerial, remotePaths);
}

export function DisableMultiplePackages(packageNames: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(2373593656, packageNames);
}

export function DisableMultiplePackagesForDevice(expectedSerial: string, packageNames: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(654293101, expectedSerial, packageNames);
}

export function DisablePackage(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(2834719751, packageName);
}

export function DisablePackageForDevice(expectedSerial: string, packageName: string): $CancellablePromise<string> {
    return $Call.ByID(3207318068, expectedSerial, packageName);
}

export function DisconnectWireless(address: string): $CancellablePromise<string> {
    return $Call.ByID(2658892249, address);
}

export function DiscoverWireless(): $CancellablePromise<device$0.MDNSService[] | null> {
    return $Call.ByID(84615852);
}

export function DiscoverWirelessDevices(): $CancellablePromise<device$0.DiscoveredWirelessDevice[] | null> {
    return $Call.ByID(3651711663);
}

export function DownloadPlatformTools(): $CancellablePromise<void> {
    return $Call.ByID(3158826559);
}

export function DownloadScrcpy(): $CancellablePromise<void> {
    return $Call.ByID(2662949553);
}

export function EnableMultiplePackages(packageNames: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(2259882189, packageNames);
}

export function EnableMultiplePackagesForDevice(expectedSerial: string, packageNames: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(499505170, expectedSerial, packageNames);
}

export function EnablePackage(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(1723531040, packageName);
}

export function EnablePackageForDevice(expectedSerial: string, packageName: string): $CancellablePromise<string> {
    return $Call.ByID(1482858629, expectedSerial, packageName);
}

export function EnableWirelessTCPIP(port: string, serial: string): $CancellablePromise<string> {
    return $Call.ByID(1129935974, port, serial);
}

export function ExportAuditLogs(path: string): $CancellablePromise<void> {
    return $Call.ByID(1133489211, path);
}

export function ExportSettings(path: string): $CancellablePromise<void> {
    return $Call.ByID(1954015320, path);
}

/**
 * FastbootContinue boots a device out of fastboot/bootloader without a
 * physical Start/Power press (WOF - Wake on Fastboot).
 */
export function FastbootContinue(serial: string): $CancellablePromise<string> {
    return $Call.ByID(3618500392, serial);
}

export function FlashPartition(serial: string, partition: string, filePath: string): $CancellablePromise<string> {
    return $Call.ByID(1653575171, serial, partition, filePath);
}

/**
 * FlashPartitionForDevice flashes one partition to the confirmed fastboot serial.
 */
export function FlashPartitionForDevice(confirmedSerial: string, partition: string, filePath: string): $CancellablePromise<string> {
    return $Call.ByID(3034615512, confirmedSerial, partition, filePath);
}

export function FlashRomFolder(serial: string, folderPath: string, plan: flasher$0.Plan): $CancellablePromise<string> {
    return $Call.ByID(2622410499, serial, folderPath, plan);
}

/**
 * FlashRomFolderForDevice flashes a validated plan to the confirmed fastboot serial,
 * pinning one fastboot executable for every step of the batch.
 */
export function FlashRomFolderForDevice(confirmedSerial: string, folderPath: string, plan: flasher$0.Plan): $CancellablePromise<string> {
    return $Call.ByID(1043022296, confirmedSerial, folderPath, plan);
}

export function ForceStopPackage(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(3751963970, packageName);
}

export function ForceStopPackageForDevice(expectedSerial: string, packageName: string): $CancellablePromise<string> {
    return $Call.ByID(3498537535, expectedSerial, packageName);
}

export function ForgetRememberedWirelessDevice(key: string): $CancellablePromise<void> {
    return $Call.ByID(230291066, key);
}

export function GetActiveScrcpySession(): $CancellablePromise<scrcpy$0.Session | null> {
    return $Call.ByID(489230595);
}

export function GetActiveSerial(): $CancellablePromise<string> {
    return $Call.ByID(4189054855);
}

export function GetActiveSlot(serial: string): $CancellablePromise<string> {
    return $Call.ByID(2823231567, serial);
}

export function GetAppConfig(): $CancellablePromise<core$0.AppConfigSnapshot> {
    return $Call.ByID(3154339166);
}

export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(4157445708);
}

export function GetAuditLogs(limit: number): $CancellablePromise<audit$0.Entry[] | null> {
    return $Call.ByID(229985055, limit);
}

export function GetBinaryStatus(): $CancellablePromise<binary$0.BinarySetupResult | null> {
    return $Call.ByID(2536319202);
}

export function GetCapabilities(): $CancellablePromise<{ [_ in string]?: boolean } | null> {
    return $Call.ByID(1642500355);
}

export function GetConnectionDoctorReport(): $CancellablePromise<$models.ConnectionDoctorReport> {
    return $Call.ByID(1300105696);
}

export function GetDeviceInfo(serial: string): $CancellablePromise<device$0.Info | null> {
    return $Call.ByID(3142718507, serial);
}

export function GetDeviceMode(serial: string): $CancellablePromise<device$0.Mode> {
    return $Call.ByID(2763349560, serial);
}

export function GetDeviceNicknames(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2510226532);
}

export function GetDevices(): $CancellablePromise<device$0.Summary[] | null> {
    return $Call.ByID(1839259332);
}

export function GetDirectorySize(remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(1427428581, remotePath);
}

export function GetDirectorySizeForDevice(expectedSerial: string, remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(3001868666, expectedSerial, remotePath);
}

export function GetFastbootDevices(): $CancellablePromise<flasher$0.FastbootDeviceInfo[] | null> {
    return $Call.ByID(957713130);
}

export function GetHostFileSystemInfo(): $CancellablePromise<file$0.HostFileSystemInfo> {
    return $Call.ByID(1799163616);
}

export function GetLocalParentPath(localPath: string): $CancellablePromise<string> {
    return $Call.ByID(3067990763, localPath);
}

export function GetManagedBinaryDir(): $CancellablePromise<string> {
    return $Call.ByID(749185906);
}

export function GetPackageDetails(packageName: string): $CancellablePromise<packagemgr$0.Details> {
    return $Call.ByID(2421988071, packageName);
}

export function GetPackageDetailsForDevice(expectedSerial: string, packageName: string): $CancellablePromise<packagemgr$0.Details> {
    return $Call.ByID(1401391252, expectedSerial, packageName);
}

export function GetPerformanceSnapshot(serial: string): $CancellablePromise<device$0.PerformanceSnapshot> {
    return $Call.ByID(981742441, serial);
}

export function GetRememberedWirelessDevices(): $CancellablePromise<core$0.RememberedWirelessDevice[] | null> {
    return $Call.ByID(1445682174);
}

export function GetRuntimeDiagnostics(): $CancellablePromise<core$0.RuntimeDiagnostics> {
    return $Call.ByID(1841691581);
}

export function GetSafeTuningFeedConfig(): $CancellablePromise<tuning$0.FeedConfig> {
    return $Call.ByID(85208519);
}

export function GetSafeTuningFeedStatus(): $CancellablePromise<tuning$0.FeedStatus> {
    return $Call.ByID(2606776047);
}

export function GetScrcpyClipboard(serial: string): $CancellablePromise<string> {
    return $Call.ByID(2301369359, serial);
}

export function GetScrcpyEncoderSupport(serial: string): $CancellablePromise<scrcpy$0.EncoderSupport | null> {
    return $Call.ByID(193742080, serial);
}

export function GetSetupState(): $CancellablePromise<binary$0.SetupState | null> {
    return $Call.ByID(78318919);
}

/**
 * GetStayAwakeWhileCharging reports the current "Stay awake" setting state.
 */
export function GetStayAwakeWhileCharging(serial: string): $CancellablePromise<boolean> {
    return $Call.ByID(1530244479, serial);
}

export function GetStorageInfo(): $CancellablePromise<file$0.StorageInfo> {
    return $Call.ByID(671426754);
}

export function GetStorageInfoForDevice(expectedSerial: string): $CancellablePromise<file$0.StorageInfo> {
    return $Call.ByID(3470748863, expectedSerial);
}

/**
 * GetWindowState returns the user's preferred window state ("maximised",
 * "normal", or "fullscreen"). The state is read from a small window.json
 * file in the data directory so main.go can also read it synchronously
 * before the Wails WebviewWindow is created.
 */
export function GetWindowState(): $CancellablePromise<string> {
    return $Call.ByID(3341756802);
}

/**
 * GetWirelessDiagnostics performs non-destructive checks for the TV Wireless
 * ADB workflow. selector may be a discovered host/IP, mDNS instance or endpoint.
 * An empty selector is accepted when exactly one device host is discovered.
 */
export function GetWirelessDiagnostics(selector: string): $CancellablePromise<$models.WirelessDiagnosticsReport> {
    return $Call.ByID(3649810751, selector);
}

export function GetWirelessHistory(): $CancellablePromise<core$0.WirelessHistoryEntry[] | null> {
    return $Call.ByID(2096684807);
}

export function ImportAuditLogs(path: string): $CancellablePromise<number> {
    return $Call.ByID(3429852810, path);
}

export function ImportSettings(path: string): $CancellablePromise<core$0.AppConfigSnapshot> {
    return $Call.ByID(1808926483, path);
}

export function InstallPackage(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(3740894366, filePath);
}

export function InstallPackageWithMode(filePath: string, mode: string): $CancellablePromise<string> {
    return $Call.ByID(677021697, filePath, mode);
}

export function InstallPackageWithModeForDevice(expectedSerial: string, filePath: string, mode: string): $CancellablePromise<string> {
    return $Call.ByID(3267609358, expectedSerial, filePath, mode);
}

export function InstallPackagesWithMode(filePaths: string[] | null, mode: string): $CancellablePromise<string> {
    return $Call.ByID(336036536, filePaths, mode);
}

export function InstallPackagesWithModeForDevice(expectedSerial: string, filePaths: string[] | null, mode: string): $CancellablePromise<string> {
    return $Call.ByID(1166719469, expectedSerial, filePaths, mode);
}

export function IsUserspaceFastboot(serial: string): $CancellablePromise<boolean> {
    return $Call.ByID(1179464884, serial);
}

export function LaunchPackage(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(3595758248, packageName);
}

export function LaunchPackageForDevice(expectedSerial: string, packageName: string): $CancellablePromise<string> {
    return $Call.ByID(2026625981, expectedSerial, packageName);
}

export function ListFiles(remotePath: string, showHidden: boolean): $CancellablePromise<file$0.Entry[] | null> {
    return $Call.ByID(251904534, remotePath, showHidden);
}

export function ListFilesForDevice(expectedSerial: string, remotePath: string, showHidden: boolean): $CancellablePromise<file$0.Entry[] | null> {
    return $Call.ByID(223609835, expectedSerial, remotePath, showHidden);
}

export function ListLocalFiles(localPath: string, showHidden: boolean): $CancellablePromise<file$0.Entry[] | null> {
    return $Call.ByID(1598426753, localPath, showHidden);
}

export function ListManagedBinaries(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2241672117);
}

export function ListPackages(filterType: string): $CancellablePromise<packagemgr$0.Info[] | null> {
    return $Call.ByID(3630353506, filterType);
}

export function ListPackagesForDevice(expectedSerial: string, filterType: string): $CancellablePromise<packagemgr$0.Info[] | null> {
    return $Call.ByID(2816869855, expectedSerial, filterType);
}

export function ListSdCards(): $CancellablePromise<file$0.SdCard[] | null> {
    return $Call.ByID(1531114407);
}

export function ListSdCardsForDevice(expectedSerial: string): $CancellablePromise<file$0.SdCard[] | null> {
    return $Call.ByID(2903613268, expectedSerial);
}

export function ListTuningSnapshots(): $CancellablePromise<tuning$0.SnapshotSummary[] | null> {
    return $Call.ByID(2377680159);
}

export function ListTuningSnapshotsForDevice(serial: string): $CancellablePromise<tuning$0.SnapshotSummary[] | null> {
    return $Call.ByID(2648452860, serial);
}

/**
 * OpenPathLocation opens a configured binary or directory in the host file
 * manager. For files, platforms that support it highlight the file; Linux
 * falls back to opening the containing directory.
 */
export function OpenPathLocation(path: string): $CancellablePromise<void> {
    return $Call.ByID(1728850843, path);
}

export function PairAndConnectWireless(selector: string, code: string): $CancellablePromise<device$0.WirelessPairAndConnectResult> {
    return $Call.ByID(962886, selector, code);
}

export function PairDiscoveredWireless(selector: string, code: string): $CancellablePromise<device$0.WirelessPairResult> {
    return $Call.ByID(3221402705, selector, code);
}

export function PairWireless(address: string, code: string): $CancellablePromise<string> {
    return $Call.ByID(2112472723, address, code);
}

/**
 * PreflightLauncher is the read-only capability picture for one confirmed device.
 */
export function PreflightLauncher(expectedSerial: string): $CancellablePromise<launcher$0.Preflight> {
    return $Call.ByID(3786023866, expectedSerial);
}

export function PullFile(remotePath: string, localPath: string): $CancellablePromise<string> {
    return $Call.ByID(2408197358, remotePath, localPath);
}

export function PullFileForDevice(serial: string, remotePath: string, localPath: string): $CancellablePromise<string> {
    return $Call.ByID(2740325907, serial, remotePath, localPath);
}

export function PullMultipleFiles(remotePaths: string[] | null, localDirectory: string): $CancellablePromise<string> {
    return $Call.ByID(3212602523, remotePaths, localDirectory);
}

export function PullMultipleFilesDetailed(expectedSerial: string, remotePaths: string[] | null, localDirectory: string): $CancellablePromise<file$0.TransferBatchResult> {
    return $Call.ByID(3115446523, expectedSerial, remotePaths, localDirectory);
}

export function PullPackageApk(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(3682822686, packageName);
}

export function PullPackageApkForDevice(expectedSerial: string, packageName: string): $CancellablePromise<string> {
    return $Call.ByID(3681769827, expectedSerial, packageName);
}

export function PushFile(localPath: string, remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(2731830669, localPath, remotePath);
}

export function PushFileForDevice(serial: string, localPath: string, remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(1309369554, serial, localPath, remotePath);
}

export function PushMultipleFiles(localPaths: string[] | null, remoteDirectory: string): $CancellablePromise<string> {
    return $Call.ByID(1562821958, localPaths, remoteDirectory);
}

export function PushMultipleFilesDetailed(expectedSerial: string, localPaths: string[] | null, remoteDirectory: string): $CancellablePromise<file$0.TransferBatchResult> {
    return $Call.ByID(3069213382, expectedSerial, localPaths, remoteDirectory);
}

export function PushScrcpyClipboard(serial: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(992928109, serial, text);
}

/**
 * ReadLauncherRecovery lists durable launcher records. It is local and read-only,
 * stays available with no online device and sends no device command.
 */
export function ReadLauncherRecovery(expectedSerial: string): $CancellablePromise<launcher$0.Recovery> {
    return $Call.ByID(1830642136, expectedSerial);
}

export function RebootDevice(serial: string, mode: string): $CancellablePromise<string> {
    return $Call.ByID(1236422188, serial, mode);
}

export function RefreshSafeTuningFeed(): $CancellablePromise<tuning$0.FeedStatus> {
    return $Call.ByID(2078803722);
}

export function RenameFile(oldRemotePath: string, newRemotePath: string): $CancellablePromise<string> {
    return $Call.ByID(1724962491, oldRemotePath, newRemotePath);
}

export function RenameFileForDevice(expectedSerial: string, oldRemotePath: string, newRemotePath: string): $CancellablePromise<string> {
    return $Call.ByID(998904000, expectedSerial, oldRemotePath, newRemotePath);
}

export function RestartADBServer(): $CancellablePromise<string> {
    return $Call.ByID(4093082264);
}

/**
 * RestoreLauncher restores the recorded original HOME after a strict live admission.
 */
export function RestoreLauncher(request: launcher$0.RestoreRequest): $CancellablePromise<launcher$0.RestoreResult> {
    return $Call.ByID(2477501031, request);
}

export function RestoreTuningSnapshot(snapshotID: string): $CancellablePromise<tuning$0.RestoreResult> {
    return $Call.ByID(303356022, snapshotID);
}

export function RestoreTuningSnapshotForDevice(serial: string, snapshotID: string): $CancellablePromise<tuning$0.RestoreResult> {
    return $Call.ByID(3743555787, serial, snapshotID);
}

export function RetryBinaryDetection(): $CancellablePromise<binary$0.BinarySetupResult | null> {
    return $Call.ByID(2288452565);
}

export function RollbackSafeTuningFeed(): $CancellablePromise<tuning$0.FeedStatus> {
    return $Call.ByID(3309233295);
}

export function RunCustomFastbootCommand(serial: string, args: string): $CancellablePromise<string> {
    return $Call.ByID(990074562, serial, args);
}

export function SaveLogcatToFile(content: string, defaultFilename: string): $CancellablePromise<void> {
    return $Call.ByID(4261422803, content, defaultFilename);
}

export function SaveWirelessHistory(entries: core$0.WirelessHistoryEntry[] | null): $CancellablePromise<void> {
    return $Call.ByID(280639586, entries);
}

export function ScanRomFolder(folderPath: string): $CancellablePromise<flasher$0.Plan | null> {
    return $Call.ByID(3708452608, folderPath);
}

export function SelectApkFile(): $CancellablePromise<string> {
    return $Call.ByID(2092370249);
}

export function SelectApkFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2384692814);
}

export function SelectBinaryFile(name: string): $CancellablePromise<string> {
    return $Call.ByID(1058415212, name);
}

export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1856580798);
}

export function SelectFile(): $CancellablePromise<string> {
    return $Call.ByID(513680857);
}

export function SelectFlashImageFile(): $CancellablePromise<string> {
    return $Call.ByID(3511365674);
}

export function SelectMultipleFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2153736906);
}

export function SelectPlatformToolsDirectory(): $CancellablePromise<dialog$0.PlatformToolsSelection | null> {
    return $Call.ByID(3336253378);
}

export function SelectSavePath(defaultFilename: string): $CancellablePromise<string> {
    return $Call.ByID(982728465, defaultFilename);
}

export function SelectScrcpyDirectory(): $CancellablePromise<dialog$0.ScrcpyDirectorySelection | null> {
    return $Call.ByID(1616760728);
}

export function SelectSideloadFile(): $CancellablePromise<string> {
    return $Call.ByID(1641148886);
}

export function SendTVRemoteKey(serial: string, key: string): $CancellablePromise<string> {
    return $Call.ByID(3400772984, serial, key);
}

export function SendTVText(serial: string, text: string): $CancellablePromise<device$0.TVTextInputResult> {
    return $Call.ByID(539502524, serial, text);
}

export function SendTerminalInput(sessionID: string, input: string): $CancellablePromise<void> {
    return $Call.ByID(2297122171, sessionID, input);
}

export function SetActiveSerial(serial: string): $CancellablePromise<void> {
    return $Call.ByID(1056503963, serial);
}

export function SetActiveSlot(serial: string, slot: string): $CancellablePromise<string> {
    return $Call.ByID(2955476459, serial, slot);
}

export function SetCustomBinary(name: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(4143077919, name, path);
}

export function SetDeviceNickname(serial: string, nickname: string): $CancellablePromise<void> {
    return $Call.ByID(1226283515, serial, nickname);
}

/**
 * SetStayAwakeWhileCharging toggles the "Stay awake" developer option so the
 * device never sleeps while charging (WOF power-button workaround).
 */
export function SetStayAwakeWhileCharging(serial: string, enabled: boolean): $CancellablePromise<string> {
    return $Call.ByID(3852606227, serial, enabled);
}

/**
 * SetWindowState persists the user's preference and returns a snapshot.
 * Empty or invalid input falls back to DefaultWindowState. The change takes
 * effect on the next app launch — live window mutation is flaky across OSes
 * and we keep this UX consistent (UI shows "takes effect on next launch").
 */
export function SetWindowState(state: string): $CancellablePromise<void> {
    return $Call.ByID(3635998518, state);
}

export function SideloadPackage(serial: string, zipPath: string): $CancellablePromise<string> {
    return $Call.ByID(333602800, serial, zipPath);
}

export function StartLogcat(serial: string, levels: string, tagFilter: string): $CancellablePromise<void> {
    return $Call.ByID(1734096891, serial, levels, tagFilter);
}

export function StartScrcpyRecording(serial: string, outputPath: string, opts: scrcpy$0.Options): $CancellablePromise<void> {
    return $Call.ByID(3564677566, serial, outputPath, opts);
}

export function StartScrcpySession(serial: string, opts: scrcpy$0.Options): $CancellablePromise<scrcpy$0.Session | null> {
    return $Call.ByID(257507581, serial, opts);
}

export function StartTerminal(serial: string): $CancellablePromise<shell$0.Session | null> {
    return $Call.ByID(441098137, serial);
}

export function StartTerminalSession(mode: string, serial: string, initialArgs: string): $CancellablePromise<shell$0.Session | null> {
    return $Call.ByID(399524219, mode, serial, initialArgs);
}

export function StopLogcat(serial: string): $CancellablePromise<void> {
    return $Call.ByID(2459045489, serial);
}

export function StopScrcpyRecording(): $CancellablePromise<string> {
    return $Call.ByID(2899130084);
}

export function StopScrcpySession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2897003951, sessionID);
}

export function TakeScrcpyScreenshot(sessionID: string, outputPath: string): $CancellablePromise<string> {
    return $Call.ByID(2289098450, sessionID, outputPath);
}

/**
 * TestLauncherCandidate opens one candidate for inspection only. It never changes
 * the default HOME.
 */
export function TestLauncherCandidate(expectedSerial: string, candidateComponent: string): $CancellablePromise<launcher$0.CandidateTestResult> {
    return $Call.ByID(1054587676, expectedSerial, candidateComponent);
}

export function UnblockPath(remotePath: string): $CancellablePromise<file$0.UnblockResult> {
    return $Call.ByID(1740768098, remotePath);
}

export function UnblockPathForDevice(expectedSerial: string, remotePath: string): $CancellablePromise<file$0.UnblockResult> {
    return $Call.ByID(2693216991, expectedSerial, remotePath);
}

export function UninstallMultiplePackages(packageNames: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(3120719178, packageNames);
}

export function UninstallMultiplePackagesForDevice(expectedSerial: string, packageNames: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(1436129591, expectedSerial, packageNames);
}

export function UninstallPackage(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(4260212121, packageName);
}

export function UninstallPackageForDevice(expectedSerial: string, packageName: string): $CancellablePromise<string> {
    return $Call.ByID(907690966, expectedSerial, packageName);
}

export function UpdatePreferences(payload: core$0.PreferencesPayload): $CancellablePromise<core$0.AppConfigSnapshot> {
    return $Call.ByID(2611727164, payload);
}

export function UpdateScrcpyOptions(options: core$0.ScrcpyOptions): $CancellablePromise<void> {
    return $Call.ByID(2464101870, options);
}

/**
 * WakeAndUnlock wakes the screen and dismisses a non-secure keyguard in one
 * call (WOF one-tap turn-on for a dead power button).
 */
export function WakeAndUnlock(serial: string): $CancellablePromise<string> {
    return $Call.ByID(653915212, serial);
}

/**
 * WakeScreen turns the device screen on via KEYCODE_WAKEUP, replacing the
 * physical power button once the device is booted.
 */
export function WakeScreen(serial: string): $CancellablePromise<string> {
    return $Call.ByID(3213671339, serial);
}

export function WipeData(serial: string): $CancellablePromise<string> {
    return $Call.ByID(858489924, serial);
}
