// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as audit$0 from "../audit/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as binary$0 from "../binary/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as device$0 from "../device/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dialog$0 from "../dialog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as file$0 from "../file/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as flasher$0 from "../flasher/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as packagemgr$0 from "../package_mgr/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scrcpy$0 from "../scrcpy/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as shell$0 from "../shell/models.js";

export function CancelFileTransfer(): $CancellablePromise<void> {
    return $Call.ByID(3540445436);
}

export function ClearAuditLogs(): $CancellablePromise<void> {
    return $Call.ByID(1675299564);
}

export function ClearCustomBinary(name: string): $CancellablePromise<void> {
    return $Call.ByID(2476663758, name);
}

export function ClearDeviceNickname(serial: string): $CancellablePromise<void> {
    return $Call.ByID(3549130150, serial);
}

export function ClearPackageData(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(875953584, packageName);
}

export function CloseTerminal(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(4124276905, sessionID);
}

export function CompleteSetup(): $CancellablePromise<binary$0.SetupState | null> {
    return $Call.ByID(455247985);
}

export function ConnectWireless(address: string): $CancellablePromise<string> {
    return $Call.ByID(1774714983, address);
}

export function CreateDirectory(remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(2415799174, remotePath);
}

export function DeleteFile(remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(1355371458, remotePath);
}

export function DeleteMultipleFiles(remotePaths: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(3099217239, remotePaths);
}

export function DisableMultiplePackages(packageNames: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(2373593656, packageNames);
}

export function DisablePackage(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(2834719751, packageName);
}

export function DisconnectWireless(address: string): $CancellablePromise<string> {
    return $Call.ByID(2658892249, address);
}

export function DownloadPlatformTools(): $CancellablePromise<void> {
    return $Call.ByID(3158826559);
}

export function DownloadScrcpy(): $CancellablePromise<void> {
    return $Call.ByID(2662949553);
}

export function EnableMultiplePackages(packageNames: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(2259882189, packageNames);
}

export function EnablePackage(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(1723531040, packageName);
}

export function EnableWirelessTCPIP(port: string, serial: string): $CancellablePromise<string> {
    return $Call.ByID(1129935974, port, serial);
}

export function ExportAuditLogs(path: string): $CancellablePromise<void> {
    return $Call.ByID(1133489211, path);
}

/**
 * FastbootContinue boots a device out of fastboot/bootloader without a
 * physical Start/Power press (WOF - Wake on Fastboot).
 */
export function FastbootContinue(serial: string): $CancellablePromise<string> {
    return $Call.ByID(3618500392, serial);
}

export function FlashPartition(serial: string, partition: string, filePath: string): $CancellablePromise<string> {
    return $Call.ByID(1653575171, serial, partition, filePath);
}

export function FlashRomFolder(serial: string, folderPath: string, plan: flasher$0.Plan): $CancellablePromise<string> {
    return $Call.ByID(2622410499, serial, folderPath, plan);
}

export function ForceStopPackage(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(3751963970, packageName);
}

export function GetActiveScrcpySession(): $CancellablePromise<scrcpy$0.Session | null> {
    return $Call.ByID(489230595);
}

export function GetActiveSerial(): $CancellablePromise<string> {
    return $Call.ByID(4189054855);
}

export function GetActiveSlot(serial: string): $CancellablePromise<string> {
    return $Call.ByID(2823231567, serial);
}

export function GetAppConfig(): $CancellablePromise<core$0.AppConfigSnapshot> {
    return $Call.ByID(3154339166);
}

export function GetAuditLogs(limit: number): $CancellablePromise<audit$0.Entry[] | null> {
    return $Call.ByID(229985055, limit);
}

export function GetBinaryStatus(): $CancellablePromise<binary$0.BinarySetupResult | null> {
    return $Call.ByID(2536319202);
}

export function GetCapabilities(): $CancellablePromise<{ [_ in string]?: boolean } | null> {
    return $Call.ByID(1642500355);
}

export function GetDeviceInfo(serial: string): $CancellablePromise<device$0.Info | null> {
    return $Call.ByID(3142718507, serial);
}

export function GetDeviceMode(serial: string): $CancellablePromise<device$0.Mode> {
    return $Call.ByID(2763349560, serial);
}

export function GetDeviceNicknames(): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(2510226532);
}

export function GetDevices(): $CancellablePromise<device$0.Summary[] | null> {
    return $Call.ByID(1839259332);
}

export function GetDirectorySize(remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(1427428581, remotePath);
}

export function GetFastbootDevices(): $CancellablePromise<flasher$0.FastbootDeviceInfo[] | null> {
    return $Call.ByID(957713130);
}

export function GetManagedBinaryDir(): $CancellablePromise<string> {
    return $Call.ByID(749185906);
}

export function GetPackageDetails(packageName: string): $CancellablePromise<packagemgr$0.Details> {
    return $Call.ByID(2421988071, packageName);
}

export function GetPerformanceSnapshot(serial: string): $CancellablePromise<device$0.PerformanceSnapshot> {
    return $Call.ByID(981742441, serial);
}

export function GetRuntimeDiagnostics(): $CancellablePromise<core$0.RuntimeDiagnostics> {
    return $Call.ByID(1841691581);
}

export function GetScrcpyClipboard(serial: string): $CancellablePromise<string> {
    return $Call.ByID(2301369359, serial);
}

export function GetScrcpyEncoderSupport(serial: string): $CancellablePromise<scrcpy$0.EncoderSupport | null> {
    return $Call.ByID(193742080, serial);
}

export function GetSetupState(): $CancellablePromise<binary$0.SetupState | null> {
    return $Call.ByID(78318919);
}

/**
 * GetStayAwakeWhileCharging reports the current "Stay awake" setting state.
 */
export function GetStayAwakeWhileCharging(serial: string): $CancellablePromise<boolean> {
    return $Call.ByID(1530244479, serial);
}

export function GetStorageInfo(): $CancellablePromise<file$0.StorageInfo> {
    return $Call.ByID(671426754);
}

/**
 * GetWindowState returns the user's preferred window state ("maximised",
 * "normal", or "fullscreen"). The state is read from a small window.json
 * file in the data directory so main.go can also read it synchronously
 * before the Wails WebviewWindow is created.
 */
export function GetWindowState(): $CancellablePromise<string> {
    return $Call.ByID(3341756802);
}

export function GetWirelessHistory(): $CancellablePromise<core$0.WirelessHistoryEntry[] | null> {
    return $Call.ByID(2096684807);
}

export function ImportAuditLogs(path: string): $CancellablePromise<number> {
    return $Call.ByID(3429852810, path);
}

export function InstallPackage(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(3740894366, filePath);
}

export function IsUserspaceFastboot(serial: string): $CancellablePromise<boolean> {
    return $Call.ByID(1179464884, serial);
}

export function LaunchPackage(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(3595758248, packageName);
}

export function ListFiles(remotePath: string, showHidden: boolean): $CancellablePromise<file$0.Entry[] | null> {
    return $Call.ByID(251904534, remotePath, showHidden);
}

export function ListManagedBinaries(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2241672117);
}

export function ListPackages(filterType: string): $CancellablePromise<packagemgr$0.Info[] | null> {
    return $Call.ByID(3630353506, filterType);
}

export function ListSdCards(): $CancellablePromise<file$0.SdCard[] | null> {
    return $Call.ByID(1531114407);
}

export function PairWireless(address: string, code: string): $CancellablePromise<string> {
    return $Call.ByID(2112472723, address, code);
}

export function PullFile(remotePath: string, localPath: string): $CancellablePromise<string> {
    return $Call.ByID(2408197358, remotePath, localPath);
}

export function PullMultipleFiles(remotePaths: string[] | null, localDirectory: string): $CancellablePromise<string> {
    return $Call.ByID(3212602523, remotePaths, localDirectory);
}

export function PullPackageApk(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(3682822686, packageName);
}

export function PushFile(localPath: string, remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(2731830669, localPath, remotePath);
}

export function PushMultipleFiles(localPaths: string[] | null, remoteDirectory: string): $CancellablePromise<string> {
    return $Call.ByID(1562821958, localPaths, remoteDirectory);
}

export function PushScrcpyClipboard(serial: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(992928109, serial, text);
}

export function RebootDevice(serial: string, mode: string): $CancellablePromise<string> {
    return $Call.ByID(1236422188, serial, mode);
}

export function RenameFile(oldRemotePath: string, newRemotePath: string): $CancellablePromise<string> {
    return $Call.ByID(1724962491, oldRemotePath, newRemotePath);
}

export function RetryBinaryDetection(): $CancellablePromise<binary$0.BinarySetupResult | null> {
    return $Call.ByID(2288452565);
}

export function RunCustomFastbootCommand(serial: string, args: string): $CancellablePromise<string> {
    return $Call.ByID(990074562, serial, args);
}

export function SaveLogcatToFile(content: string, defaultFilename: string): $CancellablePromise<void> {
    return $Call.ByID(4261422803, content, defaultFilename);
}

export function SaveWirelessHistory(entries: core$0.WirelessHistoryEntry[] | null): $CancellablePromise<void> {
    return $Call.ByID(280639586, entries);
}

export function ScanRomFolder(folderPath: string): $CancellablePromise<flasher$0.Plan | null> {
    return $Call.ByID(3708452608, folderPath);
}

export function SelectApkFile(): $CancellablePromise<string> {
    return $Call.ByID(2092370249);
}

export function SelectBinaryFile(name: string): $CancellablePromise<string> {
    return $Call.ByID(1058415212, name);
}

export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1856580798);
}

export function SelectFile(): $CancellablePromise<string> {
    return $Call.ByID(513680857);
}

export function SelectFlashImageFile(): $CancellablePromise<string> {
    return $Call.ByID(3511365674);
}

export function SelectMultipleFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2153736906);
}

export function SelectPlatformToolsDirectory(): $CancellablePromise<dialog$0.PlatformToolsSelection | null> {
    return $Call.ByID(3336253378);
}

export function SelectSavePath(defaultFilename: string): $CancellablePromise<string> {
    return $Call.ByID(982728465, defaultFilename);
}

export function SelectScrcpyDirectory(): $CancellablePromise<dialog$0.ScrcpyDirectorySelection | null> {
    return $Call.ByID(1616760728);
}

export function SelectSideloadFile(): $CancellablePromise<string> {
    return $Call.ByID(1641148886);
}

export function SendTerminalInput(sessionID: string, input: string): $CancellablePromise<void> {
    return $Call.ByID(2297122171, sessionID, input);
}

export function SetActiveSerial(serial: string): $CancellablePromise<void> {
    return $Call.ByID(1056503963, serial);
}

export function SetActiveSlot(serial: string, slot: string): $CancellablePromise<string> {
    return $Call.ByID(2955476459, serial, slot);
}

export function SetCustomBinary(name: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(4143077919, name, path);
}

export function SetDeviceNickname(serial: string, nickname: string): $CancellablePromise<void> {
    return $Call.ByID(1226283515, serial, nickname);
}

/**
 * SetStayAwakeWhileCharging toggles the "Stay awake" developer option so the
 * device never sleeps while charging (WOF power-button workaround).
 */
export function SetStayAwakeWhileCharging(serial: string, enabled: boolean): $CancellablePromise<string> {
    return $Call.ByID(3852606227, serial, enabled);
}

/**
 * SetWindowState persists the user's preference and returns a snapshot.
 * Empty or invalid input falls back to DefaultWindowState. The change takes
 * effect on the next app launch — live window mutation is flaky across OSes
 * and we keep this UX consistent (UI shows "takes effect on next launch").
 */
export function SetWindowState(state: string): $CancellablePromise<void> {
    return $Call.ByID(3635998518, state);
}

export function SideloadPackage(serial: string, zipPath: string): $CancellablePromise<string> {
    return $Call.ByID(333602800, serial, zipPath);
}

export function StartLogcat(serial: string, levels: string, tagFilter: string): $CancellablePromise<void> {
    return $Call.ByID(1734096891, serial, levels, tagFilter);
}

export function StartScrcpyRecording(serial: string, outputPath: string, opts: scrcpy$0.Options): $CancellablePromise<void> {
    return $Call.ByID(3564677566, serial, outputPath, opts);
}

export function StartScrcpySession(serial: string, opts: scrcpy$0.Options): $CancellablePromise<scrcpy$0.Session | null> {
    return $Call.ByID(257507581, serial, opts);
}

export function StartTerminal(serial: string): $CancellablePromise<shell$0.Session | null> {
    return $Call.ByID(441098137, serial);
}

export function StartTerminalSession(mode: string, serial: string, initialArgs: string): $CancellablePromise<shell$0.Session | null> {
    return $Call.ByID(399524219, mode, serial, initialArgs);
}

export function StopLogcat(serial: string): $CancellablePromise<void> {
    return $Call.ByID(2459045489, serial);
}

export function StopScrcpyRecording(): $CancellablePromise<string> {
    return $Call.ByID(2899130084);
}

export function StopScrcpySession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2897003951, sessionID);
}

export function TakeScrcpyScreenshot(sessionID: string, outputPath: string): $CancellablePromise<string> {
    return $Call.ByID(2289098450, sessionID, outputPath);
}

export function UnblockPath(remotePath: string): $CancellablePromise<file$0.UnblockResult> {
    return $Call.ByID(1740768098, remotePath);
}

export function UninstallMultiplePackages(packageNames: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(3120719178, packageNames);
}

export function UninstallPackage(packageName: string): $CancellablePromise<string> {
    return $Call.ByID(4260212121, packageName);
}

export function UpdatePreferences(payload: core$0.PreferencesPayload): $CancellablePromise<core$0.AppConfigSnapshot> {
    return $Call.ByID(2611727164, payload);
}

export function UpdateScrcpyOptions(options: core$0.ScrcpyOptions): $CancellablePromise<void> {
    return $Call.ByID(2464101870, options);
}

/**
 * WakeAndUnlock wakes the screen and dismisses a non-secure keyguard in one
 * call (WOF one-tap turn-on for a dead power button).
 */
export function WakeAndUnlock(serial: string): $CancellablePromise<string> {
    return $Call.ByID(653915212, serial);
}

/**
 * WakeScreen turns the device screen on via KEYCODE_WAKEUP, replacing the
 * physical power button once the device is booted.
 */
export function WakeScreen(serial: string): $CancellablePromise<string> {
    return $Call.ByID(3213671339, serial);
}

export function WipeData(serial: string): $CancellablePromise<string> {
    return $Call.ByID(858489924, serial);
}
