// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as device$0 from "../device/models.js";

/**
 * AppInfo contains local build/runtime metadata for the About page.
 * It deliberately does not perform any network requests.
 */
export interface AppInfo {
    "name": string;
    "version": string;
    "description": string;
    "os": string;
    "arch": string;
    "goVersion": string;
    "wailsVersion"?: string;
    "repository": string;
    "license": string;
    "upstreamName": string;
    "upstreamUrl": string;
}

export interface ConnectionDoctorCheck {
    "id": string;
    "group": string;
    "label": string;
    "status": ConnectionDoctorStatus;
    "detail": string;
    "recommendation"?: string;
    "action"?: string;
}

export interface ConnectionDoctorReport {
    "generatedAt": string;
    "os": string;
    "arch": string;
    "healthy": boolean;
    "passCount": number;
    "warningCount": number;
    "failCount": number;
    "infoCount": number;
    "targetSerial"?: string;
    "targetModel"?: string;
    "targetMode"?: string;
    "targetState"?: string;
    "transport"?: string;
    "checks": ConnectionDoctorCheck[] | null;
}

export enum ConnectionDoctorStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ConnectionDoctorPass = "pass",
    ConnectionDoctorWarning = "warning",
    ConnectionDoctorFail = "fail",
    ConnectionDoctorInfo = "info",
};

export interface WirelessDiagnosticCheck {
    "id": string;
    "label": string;
    "status": WirelessDiagnosticStatus;
    "detail": string;
    "recommendation"?: string;
}

export enum WirelessDiagnosticStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    WirelessDiagnosticPass = "pass",
    WirelessDiagnosticWarning = "warning",
    WirelessDiagnosticFail = "fail",
    WirelessDiagnosticInfo = "info",
};

export interface WirelessDiagnosticsReport {
    "adbPath"?: string;
    "adbVersion"?: string;
    "services": device$0.MDNSService[] | null;
    "devices": device$0.DiscoveredWirelessDevice[] | null;
    "selectedHost"?: string;
    "selectedEndpoint"?: string;
    "checks": WirelessDiagnosticCheck[] | null;
    "healthy": boolean;
}

export interface WirelessReconnectReport {
    "attempted": number;
    "connected": string[] | null;
    "alreadyConnected": string[] | null;
    "unavailable": string[] | null;
    "failed": { [_ in string]?: string } | null;
}
