// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Action is the launcher-specific operation vocabulary. It deliberately does not
 * reuse the Safe Tuning disable/uninstall action enum.
 */
export enum Action {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ActionSetHome = "set-home",
    ActionRestoreHome = "restore-home",
};

/**
 * ApplyRequest asks for a confirmed HOME replacement. OperationID is generated by
 * the client so it can cancel while the synchronous call is still running.
 */
export interface ApplyRequest {
    "operationId": string;
    "expectedSerial": string;
    "expectedComponent": string;
    "candidateComponent": string;
}

/**
 * ApplyResult reports the truthful outcome of a confirmed apply.
 */
export interface ApplyResult {
    "operationId": string;
    "serial": string;
    "state": State;
    "originalComponent": string;
    "candidateComponent": string;
    "currentComponent"?: string;
    "verified": boolean;
    "rolledBack": boolean;
    "manualCommand"?: string;
    "detail"?: string;
}

/**
 * CancelRequest cancels an owned operation by explicit serial and operation ID.
 */
export interface CancelRequest {
    "operationId": string;
    "expectedSerial": string;
}

/**
 * CancelResult reports whether an owned operation was signalled.
 */
export interface CancelResult {
    "operationId": string;
    "serial": string;
    "cancelled": boolean;
}

/**
 * CandidateTestResult is the outcome of the explicit candidate launch test.
 */
export interface CandidateTestResult {
    "component": string;
    "resolved": boolean;
    "launched": boolean;
    "detail"?: string;
    "note": string;
}

/**
 * Capability records which supported commands the device actually advertises.
 */
export interface Capability {
    "status": CapabilityStatus;
    "setHomeActivity": boolean;
    "resolveActivity": boolean;
    "detail"?: string;
}

/**
 * CapabilityStatus is the outcome of the live capability probe. Unknown must never
 * be treated as supported.
 */
export enum CapabilityStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CapabilitySupported = "supported",
    CapabilityUnsupported = "unsupported",
    CapabilityUnknown = "unknown",
};

/**
 * HomeCandidate is one resolvable HOME activity with its live package state.
 */
export interface HomeCandidate {
    "component": string;
    "package": string;
    "installed": boolean;
    "enabled": boolean;
    "selected": boolean;
    "chooser"?: boolean;
}

/**
 * Identity is the read-only device summary a preflight reports. The app fills it
 * from the existing device service; the launcher package never reads props itself.
 */
export interface Identity {
    "serial": string;
    "model"?: string;
    "manufacturer"?: string;
    "codename"?: string;
    "androidVersion"?: string;
    "sdkVersion"?: string;
    "isTV"?: boolean;
}

/**
 * Preflight is the read-only report. Supported is true only when every condition
 * for a reversible HOME change was confirmed on the live device.
 */
export interface Preflight {
    "identity": Identity;
    "userId": number;
    "capability": Capability;
    "supported": boolean;
    "reason"?: string;
    "currentHome"?: string;
    "restorable": boolean;
    "homeCandidates": HomeCandidate[] | null;
    "recovery": RecordSummary[] | null;
    "manualCommand"?: string;
    "probeDetail"?: string;
}

/**
 * RecordSummary is the read-only view of a record for the recovery surface.
 */
export interface RecordSummary {
    "id": string;
    "serial": string;
    "action": Action;
    "state": State;
    "createdAt": string;
    "updatedAt": string;
    "originalComponent": string;
    "candidateComponent": string;
    "currentComponent"?: string;
    "lastError"?: string;
    "needsRecovery": boolean;
    "blocksApply": boolean;
    "manualCommand": string;
    "unreadable"?: boolean;
    "file"?: string;
}

/**
 * Recovery is the local, offline-capable recovery listing.
 */
export interface Recovery {
    "records": RecordSummary[] | null;
    "note"?: string;
}

/**
 * RestoreRequest asks to restore the original HOME of one recorded operation.
 */
export interface RestoreRequest {
    "operationId"?: string;
    "expectedSerial": string;
    "recordId": string;
}

/**
 * RestoreResult reports the truthful outcome of a restore.
 */
export interface RestoreResult {
    "recordId": string;
    "serial": string;
    "state": State;
    "restoredComponent": string;
    "currentComponent"?: string;
    "verified": boolean;
    "manualCommand"?: string;
    "detail"?: string;
}

/**
 * State is the durable record lifecycle.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StatePlanned means an intent was recorded and no device change was attempted.
     */
    StatePlanned = "planned",

    /**
     * StatePending means the mutation may have started; the outcome is unresolved.
     */
    StatePending = "pending",

    /**
     * StateApplied means the requested HOME change was applied and verified.
     */
    StateApplied = "applied",

    /**
     * StateUnknown means the device state is uncertain and must be reviewed.
     */
    StateUnknown = "unknown",

    /**
     * StateRestorePending means a rollback was requested and is unconfirmed.
     */
    StateRestorePending = "restore-pending",

    /**
     * StateRestored means the original HOME was restored and verified.
     */
    StateRestored = "restored",
};
