// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface PlatformToolsSelection {
    "directory": string;
    "adbPath": string;
    "fastbootPath": string;
}

export interface ScrcpyDirectorySelection {
    "directory": string;
    "scrcpyPath": string;
}
