// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Entry {
    "id": number;
    "timestamp": string;
    "level": LogLevel;
    "operation": string;
    "message": string;
    "details"?: string;
    "duration"?: string;
    "success": boolean;
}

export enum LogLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LogLevelInfo = "info",
    LogLevelWarning = "warning",
    LogLevelError = "error",
    LogLevelDebug = "debug",
    LogLevelSuccess = "success",
};
