// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ReleaseInfo {
    "currentVersion": string;
    "latestVersion": string;
    "updateAvailable": boolean;
    "releaseUrl": string;
    "releaseName": string;
    "publishedAt": string;
}
