// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CodecSupport {
    "codec": string;
    "encoderName": string;
    "hardware": boolean;
    "vendor": boolean;
    "softwareOnly": boolean;
    "recommended": boolean;
    "aliasOf": string;
}

export interface EncoderSupport {
    "serial": string;
    "videoCodecs": CodecSupport[] | null;
    "audioCodecs": CodecSupport[] | null;
}

export interface Options {
    "max_size": number;
    "bit_rate": number;
    "max_fps": number;
    "audio_bit_rate": number;
    "audio_codec": string;
    "video_codec": string;
    "show_touches": boolean;
    "no_audio": boolean;
    "no_control": boolean;
    "stay_awake": boolean;
    "turn_screen_off": boolean;
    "power_off_on_close": boolean;
    "fullscreen": boolean;
    "always_on_top": boolean;
    "disable_screensaver": boolean;
    "rotation": number;
    "display_id": number;
    "time_limit": number;
}

export interface Session {
    "id": string;
    "serial": string;
    "status": SessionStatus;
    "pid": number;
    "startedAt": number;
}

export interface SessionEvent {
    "sessionId": string;
    "serial": string;
    "status": SessionStatus;
    "pid"?: number;
    "message"?: string;
}

export enum SessionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusStarting = "starting",
    StatusRunning = "running",
    StatusStopping = "stopping",
    StatusStopped = "stopped",
    StatusError = "error",
};
