// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum ActionMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ActionDisable = "disable",
    ActionUninstallUser = "uninstall-user",
};

export interface Analysis {
    "serial": string;
    "hardwareSerial"?: string;
    "model": string;
    "manufacturer": string;
    "androidVersion": string;
    "isTV": boolean;
    "selectedProfile": ProfileSummary;
    "availableProfiles": ProfileSummary[] | null;
    "matches": PackageMatch[] | null;
    "installedCount": number;
    "defaultSelected": string[] | null;
    "protectedInstalled": string[] | null;
}

export interface ApplyRequest {
    "expectedSerial": string;
    "expectedHardwareSerial"?: string;
    "profileId": string;
    "packageNames": string[] | null;
    "mode": ActionMode;
    "acknowledgeCaution": boolean;
}

export interface ApplyResult {
    "snapshotId": string;
    "changed": string[] | null;
    "skipped": string[] | null;
    "failed": { [_ in string]?: string } | null;
}

export interface FeedConfig {
    "url": string;
    "publicKey": string;
}

export interface FeedStatus {
    "configured": boolean;
    "active": boolean;
    "source": string;
    "url": string;
    "version": string;
    "revision": number;
    "generatedAt": string;
    "keyId": string;
    "digest": string;
    "sourceName": string;
    "sourceUrl": string;
    "sourceLicense": string;
    "profileCount": number;
    "canRollback": boolean;
    "message": string;
}

export interface PackageMatch {
    "packageName": string;
    "label": string;
    "category": string;
    "risk": Risk;
    "reason": string;
    "defaultSelected": boolean;
    "isEnabled": boolean;
    "isSystemApp": boolean;
    "protected": boolean;
    "actionable": boolean;
}

export interface ProfileSummary {
    "id": string;
    "name": string;
    "deviceFamily": string;
    "description": string;
    "sourceName": string;
    "sourceUrl": string;
    "sourceLicense": string;
    "matchScore": number;
    "recommended": boolean;
}

export interface RestoreResult {
    "snapshotId": string;
    "restored": string[] | null;
    "failed": { [_ in string]?: string } | null;
}

export enum Risk {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RiskSafe = "safe",
    RiskCaution = "caution",
    RiskDangerous = "dangerous",
    RiskBlocked = "blocked",
};

export interface SnapshotSummary {
    "version": number;
    "recoverable": number;
    "uncertain": number;
    "id": string;
    "createdAt": string;
    "serial": string;
    "profileId": string;
    "profileName": string;
    "mode": ActionMode;
    "applied": number;
}
