// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Info {
    "serial": string;
    "state": State;
    "mode": Mode;
    "product"?: string;
    "model"?: string;
    "device"?: string;
    "brand"?: string;
    "codename"?: string;
    "manufacturer"?: string;
    "androidVersion"?: string;
    "sdkVersion"?: string;
    "buildId"?: string;
    "securityPatch"?: string;
    "abis"?: string;
    "transportId"?: string;
    "connectionLabel"?: string;
    "ipAddress"?: string;
    "rootStatus"?: string;
    "batteryLevel"?: string;
    "storageInfo"?: string;
    "ramTotal"?: string;
}

export enum Mode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ModeADB = "adb",
    ModeFastboot = "fastboot",
    ModeUnknown = "unknown",
};

export interface PerformanceSnapshot {
    "serial": string;
    "cpuUsage": number;
    "ramUsage": number;
    "ramUsedBytes"?: number;
    "ramTotalBytes"?: number;
    "networkRxBytes"?: number;
    "networkTxBytes"?: number;
    "networkRxSec": number;
    "networkTxSec": number;
    "batteryLevel"?: number;
    "batteryTemperatureC"?: number;
    "storageUsedBytes"?: number;
    "storageTotalBytes"?: number;
    "uptimeSeconds"?: number;
}

export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateReady = "device",
    StateOffline = "offline",
    StateUnauthorized = "unauthorized",
    StateRecovery = "recovery",
    StateSideload = "sideload",
    StateFastboot = "fastboot",
    StateUnknown = "unknown",
};

export interface Summary {
    "serial": string;
    "state": State;
    "mode": Mode;
    "product"?: string;
    "model"?: string;
    "device"?: string;
    "transportId"?: string;
}
