// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiscoveredWirelessDevice groups the raw ADB mDNS records currently advertised
 * by one network host. It is intentionally a discovery/session model, not a
 * persistent device identity: DHCP addresses and mDNS instance names can change.
 * 
 * Once the device is connected, TVADB Hub will enrich this with the ADB serial
 * and Android properties for a more stable remembered-device identity.
 */
export interface DiscoveredWirelessDevice {
    "discoveryKey": string;
    "host": string;
    "instanceNames": string[] | null;
    "pairingAddress"?: string;
    "connectAddress"?: string;
    "legacyAddress"?: string;
    "preferredAddress"?: string;
    "secureConnect": boolean;

    /**
     * ConnectInstanceNames lists only the mDNS instance names that advertise the
     * chosen connect endpoint of the chosen kind: the unique TLS connect endpoint
     * when one is advertised, otherwise the unique legacy endpoint. It is the
     * evidence that may tie an authorized transport to this endpoint. InstanceNames
     * stays the unfiltered diagnostic view and must never be used that way.
     */
    "connectInstanceNames"?: string[] | null;

    /**
     * Derived convenience fields for the UI. PairingPort is the advertised
     * temporary pairing port. NeedsPairing means pairing is currently OFFERED
     * (a pairing endpoint exists); it is not proof that this host is not already
     * paired. ConnectPort is the port of the preferred connect endpoint.
     */
    "pairingPort"?: number;
    "connectPort"?: number;
    "needsPairing": boolean;
}

export interface Info {
    "serial": string;
    "hardwareSerial"?: string;
    "state": State;
    "mode": Mode;
    "product"?: string;
    "model"?: string;
    "device"?: string;
    "brand"?: string;
    "codename"?: string;
    "manufacturer"?: string;
    "characteristics"?: string;
    "isTV"?: boolean;
    "androidVersion"?: string;
    "sdkVersion"?: string;
    "buildId"?: string;
    "securityPatch"?: string;
    "abis"?: string;
    "transportId"?: string;
    "connectionLabel"?: string;
    "ipAddress"?: string;
    "rootStatus"?: string;
    "batteryLevel"?: string;
    "storageInfo"?: string;
    "ramTotal"?: string;
}

/**
 * MDNSService is one ADB service advertised on the local network.
 * 
 * Modern Android wireless debugging advertises two TLS services:
 *   - _adb-tls-pairing._tcp while the pairing-code screen is open
 *   - _adb-tls-connect._tcp for normal authenticated ADB connections
 * 
 * Older devices can advertise the legacy _adb._tcp service instead.
 */
export interface MDNSService {
    "instanceName": string;
    "serviceName": string;
    "kind": MDNSServiceKind;
    "address": string;
    "host": string;
    "port": string;
    "secure": boolean;
}

export enum MDNSServiceKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MDNSServicePairing = "pairing",
    MDNSServiceConnect = "connect",
    MDNSServiceLegacy = "legacy",
};

export enum Mode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ModeADB = "adb",
    ModeFastboot = "fastboot",
    ModeUnknown = "unknown",
};

export interface PerformanceSnapshot {
    "serial": string;
    "cpuUsage": number;
    "ramUsage": number;
    "ramUsedBytes"?: number;
    "ramTotalBytes"?: number;
    "networkRxBytes"?: number;
    "networkTxBytes"?: number;
    "networkRxSec": number;
    "networkTxSec": number;
    "batteryLevel"?: number;
    "batteryTemperatureC"?: number;
    "storageUsedBytes"?: number;
    "storageTotalBytes"?: number;
    "uptimeSeconds"?: number;
}

export interface ScreenshotResult {
    "path": string;
    "bytes": number;
}

export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateReady = "device",
    StateOffline = "offline",
    StateUnauthorized = "unauthorized",
    StateRecovery = "recovery",
    StateSideload = "sideload",
    StateFastboot = "fastboot",
    StateUnknown = "unknown",
};

export interface Summary {
    "serial": string;
    "state": State;
    "mode": Mode;
    "product"?: string;
    "model"?: string;
    "device"?: string;
    "transportId"?: string;
}

export interface TVTextInputResult {
    "method": string;
    "detail": string;
}

export interface WirelessConnectResult {
    "service": MDNSService;
    "message": string;
}

export interface WirelessPairAndConnectResult {
    "pairingService": MDNSService;
    "connectService": MDNSService;
    "pairMessage": string;
    "connectMessage": string;
}

export interface WirelessPairResult {
    "service": MDNSService;
    "message": string;
}
