// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface LogcatEntry {
    "id": string;
    "serial": string;
    "date": string;
    "time": string;
    "pid": string;
    "tid": string;
    "level": string;
    "tag": string;
    "message": string;
    "raw": string;
    "timestamp": string;
}

export interface LogcatStatusEvent {
    "serial": string;
    "status": string;
}

export interface Session {
    "id": string;
    "serial": string;
    "mode": string;
}
