// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Details {
    "packageName": string;
    "versionName": string;
    "versionCode": string;
    "apkSizeBytes": number;
    "dataSizeBytes": number;
    "totalSizeBytes": number;
}

export interface Info {
    "packageName": string;
    "isEnabled": boolean;
    "isSystemApp": boolean;
}
