// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as device$0 from "../device/models.js";

export interface FastbootDeviceInfo {
    "serial": string;
    "state": device$0.State;
    "mode": device$0.Mode;
}

export interface Plan {
    "steps": Step[] | null;
}

export interface Step {
    "partition": string;
    "image_file": string;
}

export interface StepStatus {
    "partition": string;
    "status": string;
    "message": string;
}
